apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
data:
  OPENCLAW_HOST: "{{ .Values.env.OPENCLAW_HOST }}"
  OPENCLAW_PORT: "{{ .Values.env.OPENCLAW_PORT }}"
  OPENCLAW_ENABLE_ZEROCONF: "{{ .Values.env.OPENCLAW_ENABLE_ZEROCONF }}"
